store/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('remove/<product_id>/', views.CartRemove, name='CartRemove'),
    path('add/<product_id>/', views.CartAdd, name='CartAdd'),
    path('', views.CartDetail, name='CartDetail'),
]

store/catalog/urls.py
from django.urls import path
from . import views


app_name = 'catalog'
urlpatterns = [
    path('<category_slug>/', views.ProductList, name='ProductListByCategory'),
    path('<id>/<slug>/', views.ProductDetail, name='ProductDetail'),
    path('', views.ProductList, name='ProductList'),
]

store/store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('catalog.urls', namespace='catalog')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/cart/models.py
from django.db import models

# Create your models here.

store/catalog/models.py
from django.db import models
import uuid
from PIL import Image
from django.urls import reverse
# Create your models here.


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200, verbose_name='Название категории')
    slug = models.SlugField(max_length=200, db_index=True,
                            unique=True, blank=True, null=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def get_absolute_url(self):
        return reverse('catalog:ProductListByCategory', args=[self.slug])

    def __str__(self):
        return '{}'.format(self.name)


class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, blank=True, null=True)
    img = models.ImageField(upload_to='uploads')
    price = models.DecimalField(max_digits=11, decimal_places=2)
    specification = models.TextField(
        verbose_name='Описание товара', blank=True, null=True)
    name = models.CharField(max_length=200, verbose_name='Название товара')
    slug = models.SlugField(max_length=200, db_index=True,
                            unique=True, blank=True, null=True)
    stock = models.PositiveIntegerField(verbose_name="На складе")

    class Meta:
        ordering = ['name']
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = [
            ['id', 'slug']
        ]

    def get_absolute_url(self):
        return reverse('catalog:ProductDetail', args=[self.id, self.slug])

    def __str__(self):
        return '{} {}'.format(self.name, self.price)

store/user/models.py
from django.db import models
import uuid
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    phone_number = models.CharField(
        max_length=11, verbose_name='Личный номер', blank=True)
    
    def __str__(self):
        return '{} {} {} {}'.format(self.username, self.first_name, self.last_name, self.phone_number)

store/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

store/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from catalog.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.views.decorators.csrf import csrf_exempt
# Create your views here.


@require_POST
@csrf_exempt
def CartAdd(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:CartDetail')


def CartRemove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:CartDetail')


def CartDetail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

store/catalog/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import Category, Product
from cart.forms import CartAddProductForm

# Страница с товарами


def ProductList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.all()
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'catalog/product/list.html', {
        'category': category,
        'categories': categories,
        'products': products
    })


# Страница товара
def ProductDetail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug)
    cart_product_form = CartAddProductForm()
    return render(request, 'catalog/product/detail.html',
                              {'product': product,
                               'cart_product_form': cart_product_form})

store/user/views.py
from django.shortcuts import render

# Create your views here.

store/cart/templates/cart/detail.html
{% extends "catalog/base.html" %}
{% block title %}
  Ваша корзина товаров
{% endblock %}
{% block content %}
  <h1>Ваша корзина товаров</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Продукт</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{{ product.img.url }}" alt="" />
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>{{ item.quantity }}</td>
            <td><a href="{% url "cart:CartRemove" product.id %}">Удалить</a></td>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}
      {% endfor %}
        <tr class="total">
          <td>Total</td>
          <td colspan="4"></td>
          <td class="num">{{ cart.get_total_price }} руб.</td>
        </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url "catalog:ProductList"%}" class="btn">Продолжить Шопинг</a>
    <a href="#">Оформить заказ</a>
  </p>
{% endblock %}

store/catalog/templates/catalog/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
  <!-- Bootstrap -->
{% load bootstrap3 %}
<script src="{% bootstrap_jquery_url %}"></script> 
{% bootstrap_javascript %} 
{% bootstrap_css %}
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  
</head>
<body>
  <section id="header">
    <div class="top container">
      Мой Онлайн-Магазин
    </div>
    <div class="top-bl">
      <div class="container">
        <div class="cart">Ваша корзина пуста</div>
      </div>
    </div>
  </section>
  <section id="content row" class="container">
    {% block content %}{% endblock %}
  </section>
</body>
</html>

store/catalog/templates/catalog/product/detail.html
{% extends "catalog/base.html" %}
{% load staticfiles %}
{% block title %}
  {{ product.name }}
{% endblock %}
{% block content %}
  <p class="price">{{ product.price }} руб.</p>
  <form action="{% url "cart:CartAdd" product.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Добавить в корзину">
  </form>
  <div class="product-detail">
    <div class="col-sm-4">
      <img src="{% if product.img %}{{ product.img.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
    </div>
    <div class="col-sm-8">
      <h1>{{ product.name }}</h1>
      <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
      <p class="price">
        {{ product.price }} руб.
      </p>
      <span>
        {{ product.description | linebreaks}}
      </span>
    </div>
  </div>
{% endblock %}

store/catalog/templates/catalog/product/list.html
{% extends 'catalog/base.html' %}
{% load staticfiles %}
{% block title %}
  {% if category %} {{ category.name }} {% else %} Страница товаров {% endif %}
{% endblock %}
{% block content %}
  <div id="sidebar" class="col-sm-3">
    <h3>Категории</h3>
    <ul class="list-group">
      <li {% if not category %} class="list-group-item selected" {%else%}class="list-group-item disabled" {% endif %}>
        <a href="{% url "catalog:ProductList" %}">Все</a>
      </li>
      {% for cat in categories %}
        <li {% if category.slug == cat.slug %} class="list-group-item selected" {%else%}class="list-group-item disabled" {% endif %}>
          <a href="{{ cat.get_absolute_url }}">{{ cat.name }}</a>
        </li>
      {% endfor %}
    </ul>
  </div>
  <div id="main" class="product_list col-sm-9">
    <h1>{% if category %}{{ category.name }}{% else %}Товары{% endif %}</h1>
    <div class="items row">
      {% for product in products %}
        <div class="item col-sm-4">
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.img %}{{ product.img.url }}{% else %}{% static "img/no-image.jpg"%}{% endif %}" class="img-responsive">
          </a>
          <a href="{{ product.get_absolute_url }}">{{ product.name }}</a><br>
          {{ product.price }} руб.
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}</code>
</pre>

store/catalog/templates/catalog/product_list.html
{% extends 'catalog/base.html' %}
{% block content %}
<div class="row">
    <div class="col-sm-0 "></div>
    <div class="col-sm-11 page-header" style="margin-left: 4%;">
        <h2 class="text-center">Catalog</h2>
    </div>
    <div class="col-sm-1"></div>
</div>
<div class="row">
    <div class="col-sm-0"></div>

    <div class="col-sm-11 panel panel-primary" style="margin-left: 4%;">
               
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Категория</th>
                    <th>Название</th>
                    <th>Цена</th>
                    <th>Количество</th>
                </tr>
                
            </thead>
            <tbody class="paleblue">
                {% if catalog %} 
                    {% for product in catalog %} 
                        <tr>
                            <td>{{ product.category}}</td>
                            <td>{{ product.name}}</td>
                            <td>{{ product.price}}</td>
                            <td>{{ product.stock}}</td>
                                                       
                        </tr>

                        {% endfor %} 
                        {% endif %}
            </tbody>
        </table>

        
    </div>

    <div class="col-sm-1"></div>

</div>

{% endblock %}